! This file was automatically generated by SWIG (https://www.swig.org).
! Version 4.2.0
!
! Do not make changes to this file unless you know what you are doing - modify
! the SWIG interface file instead.
module cola
 use, intrinsic :: ISO_C_BINDING
 implicit none
 private

 ! DECLARATION CONSTRUCTS

 integer, parameter :: swig_cmem_own_bit = 0
 integer, parameter :: swig_cmem_rvalue_bit = 1
 type, bind(C) :: SwigClassWrapper
  type(C_PTR), public :: cptr = C_NULL_PTR
  integer(C_INT), public :: cmemflags = 0
 end type
 type, public :: SWIGTYPE_p_uint16_t
  type(SwigClassWrapper), public :: swigdata
 end type
 ! struct std::pair< uint16_t,uint16_t >
 type, public :: AZ
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_first => swigf_AZ_first_set
  procedure :: get_first => swigf_AZ_first_get
  procedure :: set_second => swigf_AZ_second_set
  procedure :: get_second => swigf_AZ_second_get
  procedure :: release => swigf_AZ_release
  procedure, private :: swigf_AZ_op_assign__
  generic :: assignment(=) => swigf_AZ_op_assign__
 end type AZ
 type, public :: SWIGTYPE_p_std__pairT_std__string_std__string_t
  type(SwigClassWrapper), public :: swigdata
 end type
 ! class std::vector< std::pair< std::string,std::string > >
 type, public :: ParametersMap
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: size => swigf_ParametersMap_size
  procedure :: capacity => swigf_ParametersMap_capacity
  procedure :: empty => swigf_ParametersMap_empty
  procedure :: front => swigf_ParametersMap_front
  procedure :: back => swigf_ParametersMap_back
  procedure :: reserve => swigf_ParametersMap_reserve
  procedure, private :: swigf_ParametersMap_resize__SWIG_0
  procedure, private :: swigf_ParametersMap_resize__SWIG_1
  procedure :: push_back => swigf_ParametersMap_push_back
  procedure :: pop_back => swigf_ParametersMap_pop_back
  procedure :: clear => swigf_ParametersMap_clear
  procedure :: set => swigf_ParametersMap_set
  procedure :: get => swigf_ParametersMap_get
  procedure :: insert => swigf_ParametersMap_insert
  procedure, private :: swigf_ParametersMap_erase__SWIG_0
  procedure, private :: swigf_ParametersMap_erase__SWIG_1
  procedure :: front_ref => swigf_ParametersMap_front_ref
  procedure :: back_ref => swigf_ParametersMap_back_ref
  procedure :: get_ref => swigf_ParametersMap_get_ref
  procedure :: release => swigf_ParametersMap_release
  procedure, private :: swigf_ParametersMap_op_assign__
  generic :: resize => swigf_ParametersMap_resize__SWIG_0, swigf_ParametersMap_resize__SWIG_1
  generic :: assignment(=) => swigf_ParametersMap_op_assign__
  generic :: erase => swigf_ParametersMap_erase__SWIG_0, swigf_ParametersMap_erase__SWIG_1
 end type ParametersMap
 ! class std::vector< cola::Particle >
 type, public :: EventParticles
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: size => swigf_EventParticles_size
  procedure :: capacity => swigf_EventParticles_capacity
  procedure :: empty => swigf_EventParticles_empty
  procedure :: front => swigf_EventParticles_front
  procedure :: back => swigf_EventParticles_back
  procedure :: reserve => swigf_EventParticles_reserve
  procedure, private :: swigf_EventParticles_resize__SWIG_0
  procedure, private :: swigf_EventParticles_resize__SWIG_1
  procedure :: push_back => swigf_EventParticles_push_back
  procedure :: pop_back => swigf_EventParticles_pop_back
  procedure :: clear => swigf_EventParticles_clear
  procedure :: set => swigf_EventParticles_set
  procedure :: get => swigf_EventParticles_get
  procedure :: insert => swigf_EventParticles_insert
  procedure, private :: swigf_EventParticles_erase__SWIG_0
  procedure, private :: swigf_EventParticles_erase__SWIG_1
  procedure :: front_ref => swigf_EventParticles_front_ref
  procedure :: back_ref => swigf_EventParticles_back_ref
  procedure :: get_ref => swigf_EventParticles_get_ref
  procedure :: release => swigf_EventParticles_release
  procedure, private :: swigf_EventParticles_op_assign__
  generic :: resize => swigf_EventParticles_resize__SWIG_0, swigf_EventParticles_resize__SWIG_1
  generic :: assignment(=) => swigf_EventParticles_op_assign__
  generic :: erase => swigf_EventParticles_erase__SWIG_0, swigf_EventParticles_erase__SWIG_1
 end type EventParticles
 public :: PdgToAZ
 public :: AZToPdg
 ! enum class cola::ParticleClass
 enum, bind(c)
  enumerator :: ParticleClass_PRODUCED
  enumerator :: ParticleClass_ELASTIC_A
  enumerator :: ParticleClass_ELASTIC_B
  enumerator :: ParticleClass_NONELASTIC_A
  enumerator :: ParticleClass_NONELASTIC_B
  enumerator :: ParticleClass_SPECTATOR_A
  enumerator :: ParticleClass_SPECTATOR_B
 end enum
 integer, parameter, public :: ParticleClass = kind(ParticleClass_PRODUCED)
 public :: ParticleClass_PRODUCED, ParticleClass_ELASTIC_A, ParticleClass_ELASTIC_B, ParticleClass_NONELASTIC_A, &
    ParticleClass_NONELASTIC_B, ParticleClass_SPECTATOR_A, ParticleClass_SPECTATOR_B
 type, public :: SWIGTYPE_p_LorentzVectorImplT_double_t
  type(SwigClassWrapper), public :: swigdata
 end type
 ! struct cola::Particle
 type, public :: Particle
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: GetAZ => swigf_Particle_GetAZ
  procedure :: set_position => swigf_Particle_position_set
  procedure :: get_position => swigf_Particle_position_get
  procedure :: set_momentum => swigf_Particle_momentum_set
  procedure :: get_momentum => swigf_Particle_momentum_get
  procedure :: set_pdgCode => swigf_Particle_pdgCode_set
  procedure :: get_pdgCode => swigf_Particle_pdgCode_get
  procedure :: set_pClass => swigf_Particle_pClass_set
  procedure :: get_pClass => swigf_Particle_pClass_get
  procedure :: release => swigf_Particle_release
  procedure, private :: swigf_Particle_op_assign__
  generic :: assignment(=) => swigf_Particle_op_assign__
 end type Particle
 ! struct cola::EventIniState
 type, public :: EventIniState
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_pdgCodeA => swigf_EventIniState_pdgCodeA_set
  procedure :: get_pdgCodeA => swigf_EventIniState_pdgCodeA_get
  procedure :: set_pdgCodeB => swigf_EventIniState_pdgCodeB_set
  procedure :: get_pdgCodeB => swigf_EventIniState_pdgCodeB_get
  procedure :: set_pZA => swigf_EventIniState_pZA_set
  procedure :: get_pZA => swigf_EventIniState_pZA_get
  procedure :: set_pZB => swigf_EventIniState_pZB_set
  procedure :: get_pZB => swigf_EventIniState_pZB_get
  procedure :: set_energy => swigf_EventIniState_energy_set
  procedure :: get_energy => swigf_EventIniState_energy_get
  procedure :: set_sectNN => swigf_EventIniState_sectNN_set
  procedure :: get_sectNN => swigf_EventIniState_sectNN_get
  procedure :: set_b => swigf_EventIniState_b_set
  procedure :: get_b => swigf_EventIniState_b_get
  procedure :: set_nColl => swigf_EventIniState_nColl_set
  procedure :: get_nColl => swigf_EventIniState_nColl_get
  procedure :: set_nCollPP => swigf_EventIniState_nCollPP_set
  procedure :: get_nCollPP => swigf_EventIniState_nCollPP_get
  procedure :: set_nCollPN => swigf_EventIniState_nCollPN_set
  procedure :: get_nCollPN => swigf_EventIniState_nCollPN_get
  procedure :: set_nCollNN => swigf_EventIniState_nCollNN_set
  procedure :: get_nCollNN => swigf_EventIniState_nCollNN_get
  procedure :: set_nPart => swigf_EventIniState_nPart_set
  procedure :: get_nPart => swigf_EventIniState_nPart_get
  procedure :: set_nPartA => swigf_EventIniState_nPartA_set
  procedure :: get_nPartA => swigf_EventIniState_nPartA_get
  procedure :: set_nPartB => swigf_EventIniState_nPartB_set
  procedure :: get_nPartB => swigf_EventIniState_nPartB_get
  procedure :: set_phiRotA => swigf_EventIniState_phiRotA_set
  procedure :: get_phiRotA => swigf_EventIniState_phiRotA_get
  procedure :: set_thetaRotA => swigf_EventIniState_thetaRotA_set
  procedure :: get_thetaRotA => swigf_EventIniState_thetaRotA_get
  procedure :: set_phiRotB => swigf_EventIniState_phiRotB_set
  procedure :: get_phiRotB => swigf_EventIniState_phiRotB_get
  procedure :: set_thetaRotB => swigf_EventIniState_thetaRotB_set
  procedure :: get_thetaRotB => swigf_EventIniState_thetaRotB_get
  procedure :: set_iniStateParticles => swigf_EventIniState_iniStateParticles_set
  procedure :: get_iniStateParticles => swigf_EventIniState_iniStateParticles_get
  procedure :: release => swigf_EventIniState_release
  procedure, private :: swigf_EventIniState_op_assign__
  generic :: assignment(=) => swigf_EventIniState_op_assign__
 end type EventIniState
 ! struct cola::EventData
 type, public :: EventData
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_iniState => swigf_EventData_iniState_set
  procedure :: get_iniState => swigf_EventData_iniState_get
  procedure :: set_particles => swigf_EventData_particles_set
  procedure :: get_particles => swigf_EventData_particles_get
  procedure :: release => swigf_EventData_release
  procedure, private :: swigf_EventData_op_assign__
  generic :: assignment(=) => swigf_EventData_op_assign__
 end type EventData

  type, abstract, public :: AbstractFortranConverter
  contains
    procedure(fortran_converter_init_interface), deferred :: init
    procedure(fortran_converter_run_interface), deferred :: run
  end type AbstractFortranConverter

  type, abstract, public :: AbstractFortranGenerator
  contains
    procedure(fortran_generator_init_interface), deferred :: init
    procedure(fortran_generator_run_interface), deferred :: run
  end type AbstractFortranGenerator

  type, abstract, public :: AbstractFortranWriter
  contains
    procedure(fortran_writer_init_interface), deferred :: init
    procedure(fortran_writer_run_interface), deferred :: run
  end type AbstractFortranWriter

  abstract interface
    subroutine fortran_converter_init_interface(self, pmap)
      import :: AbstractFortranConverter, ParametersMap
      class(AbstractFortranConverter), intent(inout) :: self
      type(ParametersMap), intent(in) :: pmap
    end subroutine
    subroutine fortran_converter_run_interface(self, ed)
      import :: AbstractFortranConverter, EventData
      class(AbstractFortranConverter), intent(in) :: self
      type(EventData), intent(inout) :: ed
    end subroutine

    subroutine fortran_generator_init_interface(self, pmap)
      import :: AbstractFortranGenerator, ParametersMap
      class(AbstractFortranGenerator), intent(inout) :: self
      type(ParametersMap), intent(in) :: pmap
    end subroutine
    function fortran_generator_run_interface(self) result(ed)
      import :: AbstractFortranGenerator, EventData
      class(AbstractFortranGenerator), intent(in) :: self
      type(EventData) :: ed
    end function

    subroutine fortran_writer_init_interface(self, pmap)
      import :: AbstractFortranWriter, ParametersMap
      class(AbstractFortranWriter), intent(inout) :: self
      type(ParametersMap), intent(in) :: pmap
    end subroutine
    subroutine fortran_writer_run_interface(self, ed)
      import :: AbstractFortranWriter, EventData
      class(AbstractFortranWriter), intent(in) :: self
      type(EventData), intent(in) :: ed
    end subroutine
  end interface

 interface ParametersMap
  module procedure swigf_new_ParametersMap__SWIG_0, swigf_new_ParametersMap__SWIG_1, swigf_new_ParametersMap__SWIG_2, &
    swigf_new_ParametersMap__SWIG_3
 end interface
 interface AZ
  module procedure swigf_new_AZ__SWIG_0, swigf_new_AZ__SWIG_1, swigf_new_AZ__SWIG_2
 end interface
 interface Particle
  module procedure swigf_new_Particle
 end interface
 interface EventParticles
  module procedure swigf_new_EventParticles__SWIG_0, swigf_new_EventParticles__SWIG_1, swigf_new_EventParticles__SWIG_2, &
    swigf_new_EventParticles__SWIG_3
 end interface
 interface EventIniState
  module procedure swigf_new_EventIniState
 end interface
 interface EventData
  module procedure swigf_new_EventData
 end interface

! WRAPPER DECLARATIONS
interface
function swigc_new_AZ__SWIG_0() &
bind(C, name="_wrap_new_AZ__SWIG_0") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

function swigc_new_AZ__SWIG_1(farg1, farg2) &
bind(C, name="_wrap_new_AZ__SWIG_1") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
type(SwigClassWrapper) :: fresult
end function

function swigc_new_AZ__SWIG_2(farg1) &
bind(C, name="_wrap_new_AZ__SWIG_2") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_AZ_first_set(farg1, farg2) &
bind(C, name="_wrap_AZ_first_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

function swigc_AZ_first_get(farg1) &
bind(C, name="_wrap_AZ_first_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_AZ_second_set(farg1, farg2) &
bind(C, name="_wrap_AZ_second_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

function swigc_AZ_second_get(farg1) &
bind(C, name="_wrap_AZ_second_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_AZ(farg1) &
bind(C, name="_wrap_delete_AZ")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_AZ_op_assign__(farg1, farg2) &
bind(C, name="_wrap_AZ_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

function swigc_new_ParametersMap__SWIG_0() &
bind(C, name="_wrap_new_ParametersMap__SWIG_0") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

function swigc_new_ParametersMap__SWIG_1(farg1) &
bind(C, name="_wrap_new_ParametersMap__SWIG_1") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_new_ParametersMap__SWIG_2(farg1) &
bind(C, name="_wrap_new_ParametersMap__SWIG_2") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
integer(C_SIZE_T), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_new_ParametersMap__SWIG_3(farg1, farg2) &
bind(C, name="_wrap_new_ParametersMap__SWIG_3") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
integer(C_SIZE_T), intent(in) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
type(SwigClassWrapper) :: fresult
end function

function swigc_ParametersMap_size(farg1) &
bind(C, name="_wrap_ParametersMap_size") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIZE_T) :: fresult
end function

function swigc_ParametersMap_capacity(farg1) &
bind(C, name="_wrap_ParametersMap_capacity") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIZE_T) :: fresult
end function

function swigc_ParametersMap_empty(farg1) &
bind(C, name="_wrap_ParametersMap_empty") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

function swigc_ParametersMap_front(farg1) &
bind(C, name="_wrap_ParametersMap_front") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_ParametersMap_back(farg1) &
bind(C, name="_wrap_ParametersMap_back") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_ParametersMap_reserve(farg1, farg2) &
bind(C, name="_wrap_ParametersMap_reserve")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
end subroutine

subroutine swigc_ParametersMap_resize__SWIG_0(farg1, farg2) &
bind(C, name="_wrap_ParametersMap_resize__SWIG_0")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
end subroutine

subroutine swigc_ParametersMap_resize__SWIG_1(farg1, farg2, farg3) &
bind(C, name="_wrap_ParametersMap_resize__SWIG_1")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
type(SwigClassWrapper), intent(in) :: farg3
end subroutine

subroutine swigc_ParametersMap_push_back(farg1, farg2) &
bind(C, name="_wrap_ParametersMap_push_back")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

subroutine swigc_ParametersMap_pop_back(farg1) &
bind(C, name="_wrap_ParametersMap_pop_back")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
end subroutine

subroutine swigc_ParametersMap_clear(farg1) &
bind(C, name="_wrap_ParametersMap_clear")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
end subroutine

subroutine swigc_ParametersMap_set(farg1, farg2, farg3) &
bind(C, name="_wrap_ParametersMap_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
type(SwigClassWrapper), intent(in) :: farg3
end subroutine

function swigc_ParametersMap_get(farg1, farg2) &
bind(C, name="_wrap_ParametersMap_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_ParametersMap_insert(farg1, farg2, farg3) &
bind(C, name="_wrap_ParametersMap_insert")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
type(SwigClassWrapper), intent(in) :: farg3
end subroutine

subroutine swigc_ParametersMap_erase__SWIG_0(farg1, farg2) &
bind(C, name="_wrap_ParametersMap_erase__SWIG_0")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
end subroutine

subroutine swigc_ParametersMap_erase__SWIG_1(farg1, farg2, farg3) &
bind(C, name="_wrap_ParametersMap_erase__SWIG_1")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
integer(C_SIZE_T), intent(in) :: farg3
end subroutine

function swigc_ParametersMap_front_ref(farg1) &
bind(C, name="_wrap_ParametersMap_front_ref") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_ParametersMap_back_ref(farg1) &
bind(C, name="_wrap_ParametersMap_back_ref") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_ParametersMap_get_ref(farg1, farg2) &
bind(C, name="_wrap_ParametersMap_get_ref") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_ParametersMap(farg1) &
bind(C, name="_wrap_delete_ParametersMap")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_ParametersMap_op_assign__(farg1, farg2) &
bind(C, name="_wrap_ParametersMap_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

function swigc_new_EventParticles__SWIG_0() &
bind(C, name="_wrap_new_EventParticles__SWIG_0") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

function swigc_new_EventParticles__SWIG_1(farg1) &
bind(C, name="_wrap_new_EventParticles__SWIG_1") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_new_EventParticles__SWIG_2(farg1) &
bind(C, name="_wrap_new_EventParticles__SWIG_2") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
integer(C_SIZE_T), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_new_EventParticles__SWIG_3(farg1, farg2) &
bind(C, name="_wrap_new_EventParticles__SWIG_3") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
integer(C_SIZE_T), intent(in) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
type(SwigClassWrapper) :: fresult
end function

function swigc_EventParticles_size(farg1) &
bind(C, name="_wrap_EventParticles_size") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIZE_T) :: fresult
end function

function swigc_EventParticles_capacity(farg1) &
bind(C, name="_wrap_EventParticles_capacity") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIZE_T) :: fresult
end function

function swigc_EventParticles_empty(farg1) &
bind(C, name="_wrap_EventParticles_empty") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

function swigc_EventParticles_front(farg1) &
bind(C, name="_wrap_EventParticles_front") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_EventParticles_back(farg1) &
bind(C, name="_wrap_EventParticles_back") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_EventParticles_reserve(farg1, farg2) &
bind(C, name="_wrap_EventParticles_reserve")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
end subroutine

subroutine swigc_EventParticles_resize__SWIG_0(farg1, farg2) &
bind(C, name="_wrap_EventParticles_resize__SWIG_0")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
end subroutine

subroutine swigc_EventParticles_resize__SWIG_1(farg1, farg2, farg3) &
bind(C, name="_wrap_EventParticles_resize__SWIG_1")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
type(SwigClassWrapper), intent(in) :: farg3
end subroutine

subroutine swigc_EventParticles_push_back(farg1, farg2) &
bind(C, name="_wrap_EventParticles_push_back")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

subroutine swigc_EventParticles_pop_back(farg1) &
bind(C, name="_wrap_EventParticles_pop_back")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
end subroutine

subroutine swigc_EventParticles_clear(farg1) &
bind(C, name="_wrap_EventParticles_clear")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
end subroutine

subroutine swigc_EventParticles_set(farg1, farg2, farg3) &
bind(C, name="_wrap_EventParticles_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
type(SwigClassWrapper), intent(in) :: farg3
end subroutine

function swigc_EventParticles_get(farg1, farg2) &
bind(C, name="_wrap_EventParticles_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_EventParticles_insert(farg1, farg2, farg3) &
bind(C, name="_wrap_EventParticles_insert")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
type(SwigClassWrapper), intent(in) :: farg3
end subroutine

subroutine swigc_EventParticles_erase__SWIG_0(farg1, farg2) &
bind(C, name="_wrap_EventParticles_erase__SWIG_0")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
end subroutine

subroutine swigc_EventParticles_erase__SWIG_1(farg1, farg2, farg3) &
bind(C, name="_wrap_EventParticles_erase__SWIG_1")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
integer(C_SIZE_T), intent(in) :: farg3
end subroutine

function swigc_EventParticles_front_ref(farg1) &
bind(C, name="_wrap_EventParticles_front_ref") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_EventParticles_back_ref(farg1) &
bind(C, name="_wrap_EventParticles_back_ref") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_EventParticles_get_ref(farg1, farg2) &
bind(C, name="_wrap_EventParticles_get_ref") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_SIZE_T), intent(in) :: farg2
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_EventParticles(farg1) &
bind(C, name="_wrap_delete_EventParticles")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_EventParticles_op_assign__(farg1, farg2) &
bind(C, name="_wrap_EventParticles_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

function swigc_PdgToAZ(farg1) &
bind(C, name="_wrap_PdgToAZ") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
integer(C_INT), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_AZToPdg(farg1) &
bind(C, name="_wrap_AZToPdg") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

function swigc_Particle_GetAZ(farg1) &
bind(C, name="_wrap_Particle_GetAZ") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_Particle_position_set(farg1, farg2) &
bind(C, name="_wrap_Particle_position_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

function swigc_Particle_position_get(farg1) &
bind(C, name="_wrap_Particle_position_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_Particle_momentum_set(farg1, farg2) &
bind(C, name="_wrap_Particle_momentum_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

function swigc_Particle_momentum_get(farg1) &
bind(C, name="_wrap_Particle_momentum_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_Particle_pdgCode_set(farg1, farg2) &
bind(C, name="_wrap_Particle_pdgCode_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_Particle_pdgCode_get(farg1) &
bind(C, name="_wrap_Particle_pdgCode_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_Particle_pClass_set(farg1, farg2) &
bind(C, name="_wrap_Particle_pClass_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_Particle_pClass_get(farg1) &
bind(C, name="_wrap_Particle_pClass_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

function swigc_new_Particle() &
bind(C, name="_wrap_new_Particle") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_Particle(farg1) &
bind(C, name="_wrap_delete_Particle")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_Particle_op_assign__(farg1, farg2) &
bind(C, name="_wrap_Particle_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

subroutine swigc_EventIniState_pdgCodeA_set(farg1, farg2) &
bind(C, name="_wrap_EventIniState_pdgCodeA_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_EventIniState_pdgCodeA_get(farg1) &
bind(C, name="_wrap_EventIniState_pdgCodeA_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_EventIniState_pdgCodeB_set(farg1, farg2) &
bind(C, name="_wrap_EventIniState_pdgCodeB_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_EventIniState_pdgCodeB_get(farg1) &
bind(C, name="_wrap_EventIniState_pdgCodeB_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_EventIniState_pZA_set(farg1, farg2) &
bind(C, name="_wrap_EventIniState_pZA_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
real(C_DOUBLE), intent(in) :: farg2
end subroutine

function swigc_EventIniState_pZA_get(farg1) &
bind(C, name="_wrap_EventIniState_pZA_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
real(C_DOUBLE) :: fresult
end function

subroutine swigc_EventIniState_pZB_set(farg1, farg2) &
bind(C, name="_wrap_EventIniState_pZB_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
real(C_DOUBLE), intent(in) :: farg2
end subroutine

function swigc_EventIniState_pZB_get(farg1) &
bind(C, name="_wrap_EventIniState_pZB_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
real(C_DOUBLE) :: fresult
end function

subroutine swigc_EventIniState_energy_set(farg1, farg2) &
bind(C, name="_wrap_EventIniState_energy_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
real(C_DOUBLE), intent(in) :: farg2
end subroutine

function swigc_EventIniState_energy_get(farg1) &
bind(C, name="_wrap_EventIniState_energy_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
real(C_DOUBLE) :: fresult
end function

subroutine swigc_EventIniState_sectNN_set(farg1, farg2) &
bind(C, name="_wrap_EventIniState_sectNN_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
real(C_FLOAT), intent(in) :: farg2
end subroutine

function swigc_EventIniState_sectNN_get(farg1) &
bind(C, name="_wrap_EventIniState_sectNN_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
real(C_FLOAT) :: fresult
end function

subroutine swigc_EventIniState_b_set(farg1, farg2) &
bind(C, name="_wrap_EventIniState_b_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
real(C_FLOAT), intent(in) :: farg2
end subroutine

function swigc_EventIniState_b_get(farg1) &
bind(C, name="_wrap_EventIniState_b_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
real(C_FLOAT) :: fresult
end function

subroutine swigc_EventIniState_nColl_set(farg1, farg2) &
bind(C, name="_wrap_EventIniState_nColl_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_EventIniState_nColl_get(farg1) &
bind(C, name="_wrap_EventIniState_nColl_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_EventIniState_nCollPP_set(farg1, farg2) &
bind(C, name="_wrap_EventIniState_nCollPP_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_EventIniState_nCollPP_get(farg1) &
bind(C, name="_wrap_EventIniState_nCollPP_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_EventIniState_nCollPN_set(farg1, farg2) &
bind(C, name="_wrap_EventIniState_nCollPN_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_EventIniState_nCollPN_get(farg1) &
bind(C, name="_wrap_EventIniState_nCollPN_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_EventIniState_nCollNN_set(farg1, farg2) &
bind(C, name="_wrap_EventIniState_nCollNN_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_EventIniState_nCollNN_get(farg1) &
bind(C, name="_wrap_EventIniState_nCollNN_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_EventIniState_nPart_set(farg1, farg2) &
bind(C, name="_wrap_EventIniState_nPart_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_EventIniState_nPart_get(farg1) &
bind(C, name="_wrap_EventIniState_nPart_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_EventIniState_nPartA_set(farg1, farg2) &
bind(C, name="_wrap_EventIniState_nPartA_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_EventIniState_nPartA_get(farg1) &
bind(C, name="_wrap_EventIniState_nPartA_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_EventIniState_nPartB_set(farg1, farg2) &
bind(C, name="_wrap_EventIniState_nPartB_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc_EventIniState_nPartB_get(farg1) &
bind(C, name="_wrap_EventIniState_nPartB_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_EventIniState_phiRotA_set(farg1, farg2) &
bind(C, name="_wrap_EventIniState_phiRotA_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
real(C_FLOAT), intent(in) :: farg2
end subroutine

function swigc_EventIniState_phiRotA_get(farg1) &
bind(C, name="_wrap_EventIniState_phiRotA_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
real(C_FLOAT) :: fresult
end function

subroutine swigc_EventIniState_thetaRotA_set(farg1, farg2) &
bind(C, name="_wrap_EventIniState_thetaRotA_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
real(C_FLOAT), intent(in) :: farg2
end subroutine

function swigc_EventIniState_thetaRotA_get(farg1) &
bind(C, name="_wrap_EventIniState_thetaRotA_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
real(C_FLOAT) :: fresult
end function

subroutine swigc_EventIniState_phiRotB_set(farg1, farg2) &
bind(C, name="_wrap_EventIniState_phiRotB_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
real(C_FLOAT), intent(in) :: farg2
end subroutine

function swigc_EventIniState_phiRotB_get(farg1) &
bind(C, name="_wrap_EventIniState_phiRotB_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
real(C_FLOAT) :: fresult
end function

subroutine swigc_EventIniState_thetaRotB_set(farg1, farg2) &
bind(C, name="_wrap_EventIniState_thetaRotB_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
real(C_FLOAT), intent(in) :: farg2
end subroutine

function swigc_EventIniState_thetaRotB_get(farg1) &
bind(C, name="_wrap_EventIniState_thetaRotB_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
real(C_FLOAT) :: fresult
end function

subroutine swigc_EventIniState_iniStateParticles_set(farg1, farg2) &
bind(C, name="_wrap_EventIniState_iniStateParticles_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

function swigc_EventIniState_iniStateParticles_get(farg1) &
bind(C, name="_wrap_EventIniState_iniStateParticles_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_new_EventIniState() &
bind(C, name="_wrap_new_EventIniState") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_EventIniState(farg1) &
bind(C, name="_wrap_delete_EventIniState")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_EventIniState_op_assign__(farg1, farg2) &
bind(C, name="_wrap_EventIniState_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

subroutine swigc_EventData_iniState_set(farg1, farg2) &
bind(C, name="_wrap_EventData_iniState_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

function swigc_EventData_iniState_get(farg1) &
bind(C, name="_wrap_EventData_iniState_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_EventData_particles_set(farg1, farg2) &
bind(C, name="_wrap_EventData_particles_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

function swigc_EventData_particles_get(farg1) &
bind(C, name="_wrap_EventData_particles_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(in) :: farg1
type(SwigClassWrapper) :: fresult
end function

function swigc_new_EventData() &
bind(C, name="_wrap_new_EventData") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: fresult
end function

subroutine swigc_delete_EventData(farg1) &
bind(C, name="_wrap_delete_EventData")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc_EventData_op_assign__(farg1, farg2) &
bind(C, name="_wrap_EventData_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper), intent(in) :: farg2
end subroutine

end interface


contains
 ! MODULE SUBPROGRAMS
function swigf_new_AZ__SWIG_0() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(AZ) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_AZ__SWIG_0()
self%swigdata = fresult
end function

function swigf_new_AZ__SWIG_1(first, second) &
result(self)
use, intrinsic :: ISO_C_BINDING
type(AZ) :: self
type(SWIGTYPE_p_uint16_t), intent(in) :: first
type(SWIGTYPE_p_uint16_t), intent(in) :: second
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = first%swigdata
farg2 = second%swigdata
fresult = swigc_new_AZ__SWIG_1(farg1, farg2)
self%swigdata = fresult
end function

function swigf_new_AZ__SWIG_2(p) &
result(self)
use, intrinsic :: ISO_C_BINDING
type(AZ) :: self
class(AZ), intent(in) :: p
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = p%swigdata
fresult = swigc_new_AZ__SWIG_2(farg1)
self%swigdata = fresult
end function

subroutine swigf_AZ_first_set(self, first)
use, intrinsic :: ISO_C_BINDING
class(AZ), intent(in) :: self
type(SWIGTYPE_p_uint16_t), intent(in) :: first
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = first%swigdata
call swigc_AZ_first_set(farg1, farg2)
end subroutine

function swigf_AZ_first_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SWIGTYPE_p_uint16_t) :: swig_result
class(AZ), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_AZ_first_get(farg1)
swig_result%swigdata = fresult
end function

subroutine swigf_AZ_second_set(self, second)
use, intrinsic :: ISO_C_BINDING
class(AZ), intent(in) :: self
type(SWIGTYPE_p_uint16_t), intent(in) :: second
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = second%swigdata
call swigc_AZ_second_set(farg1, farg2)
end subroutine

function swigf_AZ_second_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SWIGTYPE_p_uint16_t) :: swig_result
class(AZ), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_AZ_second_get(farg1)
swig_result%swigdata = fresult
end function

subroutine swigf_AZ_release(self)
use, intrinsic :: ISO_C_BINDING
class(AZ), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_AZ(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_AZ_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(AZ), intent(inout) :: self
type(AZ), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_AZ_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

function swigf_new_ParametersMap__SWIG_0() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(ParametersMap) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_ParametersMap__SWIG_0()
self%swigdata = fresult
end function

function swigf_new_ParametersMap__SWIG_1(other) &
result(self)
use, intrinsic :: ISO_C_BINDING
type(ParametersMap) :: self
class(ParametersMap), intent(in) :: other
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = other%swigdata
fresult = swigc_new_ParametersMap__SWIG_1(farg1)
self%swigdata = fresult
end function

function swigf_new_ParametersMap__SWIG_2(count) &
result(self)
use, intrinsic :: ISO_C_BINDING
type(ParametersMap) :: self
integer, intent(in) :: count
type(SwigClassWrapper) :: fresult 
integer(C_SIZE_T) :: farg1 

farg1 = int(count, C_INT)
fresult = swigc_new_ParametersMap__SWIG_2(farg1)
self%swigdata = fresult
end function

function swigf_new_ParametersMap__SWIG_3(count, v) &
result(self)
use, intrinsic :: ISO_C_BINDING
type(ParametersMap) :: self
integer, intent(in) :: count
class(SWIGTYPE_p_std__pairT_std__string_std__string_t), intent(in) :: v
type(SwigClassWrapper) :: fresult 
integer(C_SIZE_T) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = int(count, C_INT)
farg2 = v%swigdata
fresult = swigc_new_ParametersMap__SWIG_3(farg1, farg2)
self%swigdata = fresult
end function

function swigf_ParametersMap_size(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer :: swig_result
class(ParametersMap), intent(in) :: self
integer(C_SIZE_T) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_ParametersMap_size(farg1)
swig_result = int(fresult)
end function

function swigf_ParametersMap_capacity(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer :: swig_result
class(ParametersMap), intent(in) :: self
integer(C_SIZE_T) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_ParametersMap_capacity(farg1)
swig_result = int(fresult)
end function


subroutine SWIGTM_fout_bool(imout, fout)
  use, intrinsic :: ISO_C_BINDING
  integer(kind=C_INT), intent(in) :: imout
  logical, intent(out) :: fout
  fout = (imout /= 0)
end subroutine

function swigf_ParametersMap_empty(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical :: swig_result
class(ParametersMap), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_ParametersMap_empty(farg1)
call SWIGTM_fout_bool(fresult, swig_result)
end function

function swigf_ParametersMap_front(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SWIGTYPE_p_std__pairT_std__string_std__string_t) :: swig_result
class(ParametersMap), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_ParametersMap_front(farg1)
swig_result%swigdata = fresult
end function

function swigf_ParametersMap_back(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SWIGTYPE_p_std__pairT_std__string_std__string_t) :: swig_result
class(ParametersMap), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_ParametersMap_back(farg1)
swig_result%swigdata = fresult
end function

subroutine swigf_ParametersMap_reserve(self, count)
use, intrinsic :: ISO_C_BINDING
class(ParametersMap), intent(in) :: self
integer, intent(in) :: count
type(SwigClassWrapper) :: farg1 
integer(C_SIZE_T) :: farg2 

farg1 = self%swigdata
farg2 = int(count, C_INT)
call swigc_ParametersMap_reserve(farg1, farg2)
end subroutine

subroutine swigf_ParametersMap_resize__SWIG_0(self, count)
use, intrinsic :: ISO_C_BINDING
class(ParametersMap), intent(in) :: self
integer, intent(in) :: count
type(SwigClassWrapper) :: farg1 
integer(C_SIZE_T) :: farg2 

farg1 = self%swigdata
farg2 = int(count, C_INT)
call swigc_ParametersMap_resize__SWIG_0(farg1, farg2)
end subroutine

subroutine swigf_ParametersMap_resize__SWIG_1(self, count, v)
use, intrinsic :: ISO_C_BINDING
class(ParametersMap), intent(in) :: self
integer, intent(in) :: count
class(SWIGTYPE_p_std__pairT_std__string_std__string_t), intent(in) :: v
type(SwigClassWrapper) :: farg1 
integer(C_SIZE_T) :: farg2 
type(SwigClassWrapper) :: farg3 

farg1 = self%swigdata
farg2 = int(count, C_INT)
farg3 = v%swigdata
call swigc_ParametersMap_resize__SWIG_1(farg1, farg2, farg3)
end subroutine

subroutine swigf_ParametersMap_push_back(self, v)
use, intrinsic :: ISO_C_BINDING
class(ParametersMap), intent(in) :: self
class(SWIGTYPE_p_std__pairT_std__string_std__string_t), intent(in) :: v
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = v%swigdata
call swigc_ParametersMap_push_back(farg1, farg2)
end subroutine

subroutine swigf_ParametersMap_pop_back(self)
use, intrinsic :: ISO_C_BINDING
class(ParametersMap), intent(in) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
call swigc_ParametersMap_pop_back(farg1)
end subroutine

subroutine swigf_ParametersMap_clear(self)
use, intrinsic :: ISO_C_BINDING
class(ParametersMap), intent(in) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
call swigc_ParametersMap_clear(farg1)
end subroutine

subroutine swigf_ParametersMap_set(self, index, v)
use, intrinsic :: ISO_C_BINDING
class(ParametersMap), intent(in) :: self
integer, intent(in) :: index
class(SWIGTYPE_p_std__pairT_std__string_std__string_t), intent(in) :: v
type(SwigClassWrapper) :: farg1 
integer(C_SIZE_T) :: farg2 
type(SwigClassWrapper) :: farg3 

farg1 = self%swigdata
farg2 = int(index, C_INT)
farg3 = v%swigdata
call swigc_ParametersMap_set(farg1, farg2, farg3)
end subroutine

function swigf_ParametersMap_get(self, index) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SWIGTYPE_p_std__pairT_std__string_std__string_t) :: swig_result
class(ParametersMap), intent(in) :: self
integer, intent(in) :: index
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_SIZE_T) :: farg2 

farg1 = self%swigdata
farg2 = int(index, C_INT)
fresult = swigc_ParametersMap_get(farg1, farg2)
swig_result%swigdata = fresult
end function

subroutine swigf_ParametersMap_insert(self, index, v)
use, intrinsic :: ISO_C_BINDING
class(ParametersMap), intent(in) :: self
integer, intent(in) :: index
class(SWIGTYPE_p_std__pairT_std__string_std__string_t), intent(in) :: v
type(SwigClassWrapper) :: farg1 
integer(C_SIZE_T) :: farg2 
type(SwigClassWrapper) :: farg3 

farg1 = self%swigdata
farg2 = int(index, C_INT)
farg3 = v%swigdata
call swigc_ParametersMap_insert(farg1, farg2, farg3)
end subroutine

subroutine swigf_ParametersMap_erase__SWIG_0(self, index)
use, intrinsic :: ISO_C_BINDING
class(ParametersMap), intent(in) :: self
integer, intent(in) :: index
type(SwigClassWrapper) :: farg1 
integer(C_SIZE_T) :: farg2 

farg1 = self%swigdata
farg2 = int(index, C_INT)
call swigc_ParametersMap_erase__SWIG_0(farg1, farg2)
end subroutine

subroutine swigf_ParametersMap_erase__SWIG_1(self, start_index, stop_index)
use, intrinsic :: ISO_C_BINDING
class(ParametersMap), intent(in) :: self
integer, intent(in) :: start_index
integer, intent(in) :: stop_index
type(SwigClassWrapper) :: farg1 
integer(C_SIZE_T) :: farg2 
integer(C_SIZE_T) :: farg3 

farg1 = self%swigdata
farg2 = int(start_index, C_INT)
farg3 = int(stop_index, C_INT)
call swigc_ParametersMap_erase__SWIG_1(farg1, farg2, farg3)
end subroutine

function swigf_ParametersMap_front_ref(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SWIGTYPE_p_std__pairT_std__string_std__string_t) :: swig_result
class(ParametersMap), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_ParametersMap_front_ref(farg1)
swig_result%swigdata = fresult
end function

function swigf_ParametersMap_back_ref(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SWIGTYPE_p_std__pairT_std__string_std__string_t) :: swig_result
class(ParametersMap), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_ParametersMap_back_ref(farg1)
swig_result%swigdata = fresult
end function

function swigf_ParametersMap_get_ref(self, index) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SWIGTYPE_p_std__pairT_std__string_std__string_t) :: swig_result
class(ParametersMap), intent(in) :: self
integer, intent(in) :: index
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_SIZE_T) :: farg2 

farg1 = self%swigdata
farg2 = int(index, C_INT)
fresult = swigc_ParametersMap_get_ref(farg1, farg2)
swig_result%swigdata = fresult
end function

subroutine swigf_ParametersMap_release(self)
use, intrinsic :: ISO_C_BINDING
class(ParametersMap), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_ParametersMap(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_ParametersMap_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(ParametersMap), intent(inout) :: self
type(ParametersMap), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_ParametersMap_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

function swigf_new_EventParticles__SWIG_0() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(EventParticles) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_EventParticles__SWIG_0()
self%swigdata = fresult
end function

function swigf_new_EventParticles__SWIG_1(other) &
result(self)
use, intrinsic :: ISO_C_BINDING
type(EventParticles) :: self
class(EventParticles), intent(in) :: other
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = other%swigdata
fresult = swigc_new_EventParticles__SWIG_1(farg1)
self%swigdata = fresult
end function

function swigf_new_EventParticles__SWIG_2(count) &
result(self)
use, intrinsic :: ISO_C_BINDING
type(EventParticles) :: self
integer, intent(in) :: count
type(SwigClassWrapper) :: fresult 
integer(C_SIZE_T) :: farg1 

farg1 = int(count, C_INT)
fresult = swigc_new_EventParticles__SWIG_2(farg1)
self%swigdata = fresult
end function

function swigf_new_EventParticles__SWIG_3(count, v) &
result(self)
use, intrinsic :: ISO_C_BINDING
type(EventParticles) :: self
integer, intent(in) :: count
class(Particle), intent(in) :: v
type(SwigClassWrapper) :: fresult 
integer(C_SIZE_T) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = int(count, C_INT)
farg2 = v%swigdata
fresult = swigc_new_EventParticles__SWIG_3(farg1, farg2)
self%swigdata = fresult
end function

function swigf_EventParticles_size(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer :: swig_result
class(EventParticles), intent(in) :: self
integer(C_SIZE_T) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventParticles_size(farg1)
swig_result = int(fresult)
end function

function swigf_EventParticles_capacity(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer :: swig_result
class(EventParticles), intent(in) :: self
integer(C_SIZE_T) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventParticles_capacity(farg1)
swig_result = int(fresult)
end function

function swigf_EventParticles_empty(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
logical :: swig_result
class(EventParticles), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventParticles_empty(farg1)
call SWIGTM_fout_bool(fresult, swig_result)
end function

function swigf_EventParticles_front(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(Particle) :: swig_result
class(EventParticles), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventParticles_front(farg1)
swig_result%swigdata = fresult
end function

function swigf_EventParticles_back(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(Particle) :: swig_result
class(EventParticles), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventParticles_back(farg1)
swig_result%swigdata = fresult
end function

subroutine swigf_EventParticles_reserve(self, count)
use, intrinsic :: ISO_C_BINDING
class(EventParticles), intent(in) :: self
integer, intent(in) :: count
type(SwigClassWrapper) :: farg1 
integer(C_SIZE_T) :: farg2 

farg1 = self%swigdata
farg2 = int(count, C_INT)
call swigc_EventParticles_reserve(farg1, farg2)
end subroutine

subroutine swigf_EventParticles_resize__SWIG_0(self, count)
use, intrinsic :: ISO_C_BINDING
class(EventParticles), intent(in) :: self
integer, intent(in) :: count
type(SwigClassWrapper) :: farg1 
integer(C_SIZE_T) :: farg2 

farg1 = self%swigdata
farg2 = int(count, C_INT)
call swigc_EventParticles_resize__SWIG_0(farg1, farg2)
end subroutine

subroutine swigf_EventParticles_resize__SWIG_1(self, count, v)
use, intrinsic :: ISO_C_BINDING
class(EventParticles), intent(in) :: self
integer, intent(in) :: count
class(Particle), intent(in) :: v
type(SwigClassWrapper) :: farg1 
integer(C_SIZE_T) :: farg2 
type(SwigClassWrapper) :: farg3 

farg1 = self%swigdata
farg2 = int(count, C_INT)
farg3 = v%swigdata
call swigc_EventParticles_resize__SWIG_1(farg1, farg2, farg3)
end subroutine

subroutine swigf_EventParticles_push_back(self, v)
use, intrinsic :: ISO_C_BINDING
class(EventParticles), intent(in) :: self
class(Particle), intent(in) :: v
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = v%swigdata
call swigc_EventParticles_push_back(farg1, farg2)
end subroutine

subroutine swigf_EventParticles_pop_back(self)
use, intrinsic :: ISO_C_BINDING
class(EventParticles), intent(in) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
call swigc_EventParticles_pop_back(farg1)
end subroutine

subroutine swigf_EventParticles_clear(self)
use, intrinsic :: ISO_C_BINDING
class(EventParticles), intent(in) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
call swigc_EventParticles_clear(farg1)
end subroutine

subroutine swigf_EventParticles_set(self, index, v)
use, intrinsic :: ISO_C_BINDING
class(EventParticles), intent(in) :: self
integer, intent(in) :: index
class(Particle), intent(in) :: v
type(SwigClassWrapper) :: farg1 
integer(C_SIZE_T) :: farg2 
type(SwigClassWrapper) :: farg3 

farg1 = self%swigdata
farg2 = int(index, C_INT)
farg3 = v%swigdata
call swigc_EventParticles_set(farg1, farg2, farg3)
end subroutine

function swigf_EventParticles_get(self, index) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(Particle) :: swig_result
class(EventParticles), intent(in) :: self
integer, intent(in) :: index
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_SIZE_T) :: farg2 

farg1 = self%swigdata
farg2 = int(index, C_INT)
fresult = swigc_EventParticles_get(farg1, farg2)
swig_result%swigdata = fresult
end function

subroutine swigf_EventParticles_insert(self, index, v)
use, intrinsic :: ISO_C_BINDING
class(EventParticles), intent(in) :: self
integer, intent(in) :: index
class(Particle), intent(in) :: v
type(SwigClassWrapper) :: farg1 
integer(C_SIZE_T) :: farg2 
type(SwigClassWrapper) :: farg3 

farg1 = self%swigdata
farg2 = int(index, C_INT)
farg3 = v%swigdata
call swigc_EventParticles_insert(farg1, farg2, farg3)
end subroutine

subroutine swigf_EventParticles_erase__SWIG_0(self, index)
use, intrinsic :: ISO_C_BINDING
class(EventParticles), intent(in) :: self
integer, intent(in) :: index
type(SwigClassWrapper) :: farg1 
integer(C_SIZE_T) :: farg2 

farg1 = self%swigdata
farg2 = int(index, C_INT)
call swigc_EventParticles_erase__SWIG_0(farg1, farg2)
end subroutine

subroutine swigf_EventParticles_erase__SWIG_1(self, start_index, stop_index)
use, intrinsic :: ISO_C_BINDING
class(EventParticles), intent(in) :: self
integer, intent(in) :: start_index
integer, intent(in) :: stop_index
type(SwigClassWrapper) :: farg1 
integer(C_SIZE_T) :: farg2 
integer(C_SIZE_T) :: farg3 

farg1 = self%swigdata
farg2 = int(start_index, C_INT)
farg3 = int(stop_index, C_INT)
call swigc_EventParticles_erase__SWIG_1(farg1, farg2, farg3)
end subroutine

function swigf_EventParticles_front_ref(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(Particle) :: swig_result
class(EventParticles), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventParticles_front_ref(farg1)
swig_result%swigdata = fresult
end function

function swigf_EventParticles_back_ref(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(Particle) :: swig_result
class(EventParticles), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventParticles_back_ref(farg1)
swig_result%swigdata = fresult
end function

function swigf_EventParticles_get_ref(self, index) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(Particle) :: swig_result
class(EventParticles), intent(in) :: self
integer, intent(in) :: index
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 
integer(C_SIZE_T) :: farg2 

farg1 = self%swigdata
farg2 = int(index, C_INT)
fresult = swigc_EventParticles_get_ref(farg1, farg2)
swig_result%swigdata = fresult
end function

subroutine swigf_EventParticles_release(self)
use, intrinsic :: ISO_C_BINDING
class(EventParticles), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_EventParticles(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_EventParticles_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(EventParticles), intent(inout) :: self
type(EventParticles), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_EventParticles_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

function PdgToAZ(pdgcode) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(AZ) :: swig_result
integer(C_INT), intent(in) :: pdgcode
type(SwigClassWrapper) :: fresult 
integer(C_INT) :: farg1 

farg1 = pdgcode
fresult = swigc_PdgToAZ(farg1)
swig_result%swigdata = fresult
end function

function AZToPdg(data) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(AZ), intent(in) :: data
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = data%swigdata
fresult = swigc_AZToPdg(farg1)
swig_result = fresult
end function

function swigf_Particle_GetAZ(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(AZ) :: swig_result
class(Particle), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_Particle_GetAZ(farg1)
swig_result%swigdata = fresult
end function

subroutine swigf_Particle_position_set(self, position)
use, intrinsic :: ISO_C_BINDING
class(Particle), intent(in) :: self
type(SWIGTYPE_p_LorentzVectorImplT_double_t), intent(in) :: position
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = position%swigdata
call swigc_Particle_position_set(farg1, farg2)
end subroutine

function swigf_Particle_position_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SWIGTYPE_p_LorentzVectorImplT_double_t) :: swig_result
class(Particle), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_Particle_position_get(farg1)
swig_result%swigdata = fresult
end function

subroutine swigf_Particle_momentum_set(self, momentum)
use, intrinsic :: ISO_C_BINDING
class(Particle), intent(in) :: self
type(SWIGTYPE_p_LorentzVectorImplT_double_t), intent(in) :: momentum
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = momentum%swigdata
call swigc_Particle_momentum_set(farg1, farg2)
end subroutine

function swigf_Particle_momentum_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SWIGTYPE_p_LorentzVectorImplT_double_t) :: swig_result
class(Particle), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_Particle_momentum_get(farg1)
swig_result%swigdata = fresult
end function

subroutine swigf_Particle_pdgCode_set(self, pdgcode)
use, intrinsic :: ISO_C_BINDING
class(Particle), intent(in) :: self
integer(C_INT), intent(in) :: pdgcode
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = pdgcode
call swigc_Particle_pdgCode_set(farg1, farg2)
end subroutine

function swigf_Particle_pdgCode_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(Particle), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_Particle_pdgCode_get(farg1)
swig_result = fresult
end function

subroutine swigf_Particle_pClass_set(self, pclass)
use, intrinsic :: ISO_C_BINDING
class(Particle), intent(in) :: self
integer(ParticleClass), intent(in) :: pclass
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = pclass
call swigc_Particle_pClass_set(farg1, farg2)
end subroutine

function swigf_Particle_pClass_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(ParticleClass) :: swig_result
class(Particle), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_Particle_pClass_get(farg1)
swig_result = fresult
end function

function swigf_new_Particle() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(Particle) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_Particle()
self%swigdata = fresult
end function

subroutine swigf_Particle_release(self)
use, intrinsic :: ISO_C_BINDING
class(Particle), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_Particle(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_Particle_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(Particle), intent(inout) :: self
type(Particle), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_Particle_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

subroutine swigf_EventIniState_pdgCodeA_set(self, pdgcodea)
use, intrinsic :: ISO_C_BINDING
class(EventIniState), intent(in) :: self
integer(C_INT), intent(in) :: pdgcodea
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = pdgcodea
call swigc_EventIniState_pdgCodeA_set(farg1, farg2)
end subroutine

function swigf_EventIniState_pdgCodeA_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(EventIniState), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventIniState_pdgCodeA_get(farg1)
swig_result = fresult
end function

subroutine swigf_EventIniState_pdgCodeB_set(self, pdgcodeb)
use, intrinsic :: ISO_C_BINDING
class(EventIniState), intent(in) :: self
integer(C_INT), intent(in) :: pdgcodeb
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = pdgcodeb
call swigc_EventIniState_pdgCodeB_set(farg1, farg2)
end subroutine

function swigf_EventIniState_pdgCodeB_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(EventIniState), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventIniState_pdgCodeB_get(farg1)
swig_result = fresult
end function

subroutine swigf_EventIniState_pZA_set(self, pza)
use, intrinsic :: ISO_C_BINDING
class(EventIniState), intent(in) :: self
real(C_DOUBLE), intent(in) :: pza
type(SwigClassWrapper) :: farg1 
real(C_DOUBLE) :: farg2 

farg1 = self%swigdata
farg2 = pza
call swigc_EventIniState_pZA_set(farg1, farg2)
end subroutine

function swigf_EventIniState_pZA_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swig_result
class(EventIniState), intent(in) :: self
real(C_DOUBLE) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventIniState_pZA_get(farg1)
swig_result = fresult
end function

subroutine swigf_EventIniState_pZB_set(self, pzb)
use, intrinsic :: ISO_C_BINDING
class(EventIniState), intent(in) :: self
real(C_DOUBLE), intent(in) :: pzb
type(SwigClassWrapper) :: farg1 
real(C_DOUBLE) :: farg2 

farg1 = self%swigdata
farg2 = pzb
call swigc_EventIniState_pZB_set(farg1, farg2)
end subroutine

function swigf_EventIniState_pZB_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swig_result
class(EventIniState), intent(in) :: self
real(C_DOUBLE) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventIniState_pZB_get(farg1)
swig_result = fresult
end function

subroutine swigf_EventIniState_energy_set(self, energy)
use, intrinsic :: ISO_C_BINDING
class(EventIniState), intent(in) :: self
real(C_DOUBLE), intent(in) :: energy
type(SwigClassWrapper) :: farg1 
real(C_DOUBLE) :: farg2 

farg1 = self%swigdata
farg2 = energy
call swigc_EventIniState_energy_set(farg1, farg2)
end subroutine

function swigf_EventIniState_energy_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swig_result
class(EventIniState), intent(in) :: self
real(C_DOUBLE) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventIniState_energy_get(farg1)
swig_result = fresult
end function

subroutine swigf_EventIniState_sectNN_set(self, sectnn)
use, intrinsic :: ISO_C_BINDING
class(EventIniState), intent(in) :: self
real(C_FLOAT), intent(in) :: sectnn
type(SwigClassWrapper) :: farg1 
real(C_FLOAT) :: farg2 

farg1 = self%swigdata
farg2 = sectnn
call swigc_EventIniState_sectNN_set(farg1, farg2)
end subroutine

function swigf_EventIniState_sectNN_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_FLOAT) :: swig_result
class(EventIniState), intent(in) :: self
real(C_FLOAT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventIniState_sectNN_get(farg1)
swig_result = fresult
end function

subroutine swigf_EventIniState_b_set(self, b)
use, intrinsic :: ISO_C_BINDING
class(EventIniState), intent(in) :: self
real(C_FLOAT), intent(in) :: b
type(SwigClassWrapper) :: farg1 
real(C_FLOAT) :: farg2 

farg1 = self%swigdata
farg2 = b
call swigc_EventIniState_b_set(farg1, farg2)
end subroutine

function swigf_EventIniState_b_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_FLOAT) :: swig_result
class(EventIniState), intent(in) :: self
real(C_FLOAT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventIniState_b_get(farg1)
swig_result = fresult
end function

subroutine swigf_EventIniState_nColl_set(self, ncoll)
use, intrinsic :: ISO_C_BINDING
class(EventIniState), intent(in) :: self
integer(C_INT), intent(in) :: ncoll
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = ncoll
call swigc_EventIniState_nColl_set(farg1, farg2)
end subroutine

function swigf_EventIniState_nColl_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(EventIniState), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventIniState_nColl_get(farg1)
swig_result = fresult
end function

subroutine swigf_EventIniState_nCollPP_set(self, ncollpp)
use, intrinsic :: ISO_C_BINDING
class(EventIniState), intent(in) :: self
integer(C_INT), intent(in) :: ncollpp
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = ncollpp
call swigc_EventIniState_nCollPP_set(farg1, farg2)
end subroutine

function swigf_EventIniState_nCollPP_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(EventIniState), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventIniState_nCollPP_get(farg1)
swig_result = fresult
end function

subroutine swigf_EventIniState_nCollPN_set(self, ncollpn)
use, intrinsic :: ISO_C_BINDING
class(EventIniState), intent(in) :: self
integer(C_INT), intent(in) :: ncollpn
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = ncollpn
call swigc_EventIniState_nCollPN_set(farg1, farg2)
end subroutine

function swigf_EventIniState_nCollPN_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(EventIniState), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventIniState_nCollPN_get(farg1)
swig_result = fresult
end function

subroutine swigf_EventIniState_nCollNN_set(self, ncollnn)
use, intrinsic :: ISO_C_BINDING
class(EventIniState), intent(in) :: self
integer(C_INT), intent(in) :: ncollnn
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = ncollnn
call swigc_EventIniState_nCollNN_set(farg1, farg2)
end subroutine

function swigf_EventIniState_nCollNN_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(EventIniState), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventIniState_nCollNN_get(farg1)
swig_result = fresult
end function

subroutine swigf_EventIniState_nPart_set(self, npart)
use, intrinsic :: ISO_C_BINDING
class(EventIniState), intent(in) :: self
integer(C_INT), intent(in) :: npart
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = npart
call swigc_EventIniState_nPart_set(farg1, farg2)
end subroutine

function swigf_EventIniState_nPart_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(EventIniState), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventIniState_nPart_get(farg1)
swig_result = fresult
end function

subroutine swigf_EventIniState_nPartA_set(self, nparta)
use, intrinsic :: ISO_C_BINDING
class(EventIniState), intent(in) :: self
integer(C_INT), intent(in) :: nparta
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = nparta
call swigc_EventIniState_nPartA_set(farg1, farg2)
end subroutine

function swigf_EventIniState_nPartA_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(EventIniState), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventIniState_nPartA_get(farg1)
swig_result = fresult
end function

subroutine swigf_EventIniState_nPartB_set(self, npartb)
use, intrinsic :: ISO_C_BINDING
class(EventIniState), intent(in) :: self
integer(C_INT), intent(in) :: npartb
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = npartb
call swigc_EventIniState_nPartB_set(farg1, farg2)
end subroutine

function swigf_EventIniState_nPartB_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(EventIniState), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventIniState_nPartB_get(farg1)
swig_result = fresult
end function

subroutine swigf_EventIniState_phiRotA_set(self, phirota)
use, intrinsic :: ISO_C_BINDING
class(EventIniState), intent(in) :: self
real(C_FLOAT), intent(in) :: phirota
type(SwigClassWrapper) :: farg1 
real(C_FLOAT) :: farg2 

farg1 = self%swigdata
farg2 = phirota
call swigc_EventIniState_phiRotA_set(farg1, farg2)
end subroutine

function swigf_EventIniState_phiRotA_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_FLOAT) :: swig_result
class(EventIniState), intent(in) :: self
real(C_FLOAT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventIniState_phiRotA_get(farg1)
swig_result = fresult
end function

subroutine swigf_EventIniState_thetaRotA_set(self, thetarota)
use, intrinsic :: ISO_C_BINDING
class(EventIniState), intent(in) :: self
real(C_FLOAT), intent(in) :: thetarota
type(SwigClassWrapper) :: farg1 
real(C_FLOAT) :: farg2 

farg1 = self%swigdata
farg2 = thetarota
call swigc_EventIniState_thetaRotA_set(farg1, farg2)
end subroutine

function swigf_EventIniState_thetaRotA_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_FLOAT) :: swig_result
class(EventIniState), intent(in) :: self
real(C_FLOAT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventIniState_thetaRotA_get(farg1)
swig_result = fresult
end function

subroutine swigf_EventIniState_phiRotB_set(self, phirotb)
use, intrinsic :: ISO_C_BINDING
class(EventIniState), intent(in) :: self
real(C_FLOAT), intent(in) :: phirotb
type(SwigClassWrapper) :: farg1 
real(C_FLOAT) :: farg2 

farg1 = self%swigdata
farg2 = phirotb
call swigc_EventIniState_phiRotB_set(farg1, farg2)
end subroutine

function swigf_EventIniState_phiRotB_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_FLOAT) :: swig_result
class(EventIniState), intent(in) :: self
real(C_FLOAT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventIniState_phiRotB_get(farg1)
swig_result = fresult
end function

subroutine swigf_EventIniState_thetaRotB_set(self, thetarotb)
use, intrinsic :: ISO_C_BINDING
class(EventIniState), intent(in) :: self
real(C_FLOAT), intent(in) :: thetarotb
type(SwigClassWrapper) :: farg1 
real(C_FLOAT) :: farg2 

farg1 = self%swigdata
farg2 = thetarotb
call swigc_EventIniState_thetaRotB_set(farg1, farg2)
end subroutine

function swigf_EventIniState_thetaRotB_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_FLOAT) :: swig_result
class(EventIniState), intent(in) :: self
real(C_FLOAT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventIniState_thetaRotB_get(farg1)
swig_result = fresult
end function

subroutine swigf_EventIniState_iniStateParticles_set(self, inistateparticles)
use, intrinsic :: ISO_C_BINDING
class(EventIniState), intent(in) :: self
class(EventParticles), intent(in) :: inistateparticles
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = inistateparticles%swigdata
call swigc_EventIniState_iniStateParticles_set(farg1, farg2)
end subroutine

function swigf_EventIniState_iniStateParticles_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(EventParticles) :: swig_result
class(EventIniState), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventIniState_iniStateParticles_get(farg1)
swig_result%swigdata = fresult
end function

function swigf_new_EventIniState() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(EventIniState) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_EventIniState()
self%swigdata = fresult
end function

subroutine swigf_EventIniState_release(self)
use, intrinsic :: ISO_C_BINDING
class(EventIniState), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_EventIniState(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_EventIniState_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(EventIniState), intent(inout) :: self
type(EventIniState), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_EventIniState_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

subroutine swigf_EventData_iniState_set(self, inistate)
use, intrinsic :: ISO_C_BINDING
class(EventData), intent(in) :: self
class(EventIniState), intent(in) :: inistate
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = inistate%swigdata
call swigc_EventData_iniState_set(farg1, farg2)
end subroutine

function swigf_EventData_iniState_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(EventIniState) :: swig_result
class(EventData), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventData_iniState_get(farg1)
swig_result%swigdata = fresult
end function

subroutine swigf_EventData_particles_set(self, particles)
use, intrinsic :: ISO_C_BINDING
class(EventData), intent(in) :: self
class(EventParticles), intent(in) :: particles
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = particles%swigdata
call swigc_EventData_particles_set(farg1, farg2)
end subroutine

function swigf_EventData_particles_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(EventParticles) :: swig_result
class(EventData), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc_EventData_particles_get(farg1)
swig_result%swigdata = fresult
end function

function swigf_new_EventData() &
result(self)
use, intrinsic :: ISO_C_BINDING
type(EventData) :: self
type(SwigClassWrapper) :: fresult 

fresult = swigc_new_EventData()
self%swigdata = fresult
end function

subroutine swigf_EventData_release(self)
use, intrinsic :: ISO_C_BINDING
class(EventData), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete_EventData(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf_EventData_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(EventData), intent(inout) :: self
type(EventData), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc_EventData_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine


end module
